### ISSUE TITLE
String index out of range

### ISSUE THREAD

**Issue by BangL** [kayler-renslow/arma-intellij-plugin#17]
`String index out of range: -1636
java.lang.StringIndexOutOfBoundsException: String index out of range: -1636
    at java.lang.String.substring(String.java:1954)
    at com.kaylerrenslow.a3plugin.lang.sqf.providers.SQFDocTagsCompletionProvider.addCompletions(SQFDocTagsCompletionProvider.java:25)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
    at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:776)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:90)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:758)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:87)
    at com.intellij.codeInsight.completion.AsyncCompletion$$Lambda$728/620400916.run(Unknown Source)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:855)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:84)
    at com.intellij.codeInsight.completion.AsyncCompletion$$Lambda$727/1246350698.run(Unknown Source)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:82)
    at com.intellij.codeInsight.completion.AsyncCompletion$$Lambda$726/288331796.run(Unknown Source)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)`

i am getting those alot. ..feels like it happens especially when making comments, not sure.
i have to say though: i am working on a whole mod, not just a mission... and i have a shitload of files.. some are pretty big.
and i guess it might be a bit too much for the global-var check and things like that.

when i try to edit some of those biggest files (~100 lines), the whole IDE actually even freezes after some time... and thats for so long, i have to kill it. - the only way to edit those 2 or 3 files safely is using another external editor, which is.. kinda killing the point of the IDE.
not sure if those freezes are related to this overflow though.

**Comment by kayler-renslow** [comment]
Thanks for reporting the issue. I think I fixed this not to long ago, so the fix should be in place in 1.0.5

**Comment by kayler-renslow** [comment]
As for the freezing issue, what version are you using? That sounds like a 1.0.4 issue.

**Comment by BangL** [comment]
its 1.0.4_1
and it happens right in the second when i start editing any file WHILE having some specific big files open.
it doesnt even need to be the big file which im editing, just having it open is enough. pasting a 100 liner in a new file can cause the same behaviour.

maybe just dont mind this for now, i know its a horror to think about sporadic things like these.
lets see what 1.0.5 brings when its done, maybe its already fixed anyways.

**Comment by kayler-renslow** [comment]
I have a feeling it's associated with the error you posted above.

**Comment by kayler-renslow** [comment]
This is confirmed to be fixed in 1.0.5

**Comment by BangL** [comment]
@kayler-renslow 
i just want to say thank you for this plugin in general, and especially for all the fixes you made for us lately. it improved my workflow very well.
i would write a private message, but we dont have something like this on github, so i am attaching it here. so yeah.. thanks!

**Comment by kayler-renslow** [comment]
Glad you like it! This plugin makes me furious some times when I'm working on it, so it's good to hear the frustration is all for the better.
