### ISSUE TITLE
ShowArmaColorPicker Exception

### ISSUE THREAD

**Issue by Ragebone** [kayler-renslow/arma-intellij-plugin#44]
### Plugin Version
1.0.7
### Summary
Exception.
### Detail
I can't seem to find the color picker, so he's probably not loaded as the exception states.  
I'm not using it but Intelli J came at me with the exception so i thought i'd share it.

###Log 
class with name 'com.kaylerrenslow.a3plugin.dialog.actions.mainMenu.Action_ShowArmaColorPicker' cannot be loaded [Plugin: com.kaylerrenslow.plugin.armaplugin.id]
com.intellij.diagnostic.PluginException: class with name 'com.kaylerrenslow.a3plugin.dialog.actions.mainMenu.Action_ShowArmaColorPicker' cannot be loaded [Plugin: com.kaylerrenslow.plugin.armaplugin.id]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:193)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:158)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:485)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:473)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1248)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:34)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: javafx/scene/Scene
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:151)
	... 15 more
Caused by: java.lang.ClassNotFoundException: javafx.scene.Scene PluginClassLoader[com.kaylerrenslow.plugin.armaplugin.id, 1.0.7]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

**Comment by kayler-renslow** [comment]
This is a weird error. What version of Java are you using and what IntelliJ version are you using?

**Comment by Ragebone** [comment]
IntelliJ IDEA 2017.1
Build #IU-171.3780.107, built on March 22, 2017
JRE: 1.8.0_121-b13 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.10.4-1-MANJARO

**Comment by kayler-renslow** [comment]
I think I finally know the issue. For some reason, your JDK doesn't include the library that the picker uses. I don't have a user friendly solution to this problem, but maybe this will help: http://stackoverflow.com/questions/34243982/why-is-javafx-is-not-included-in-openjdk-8-on-ubuntu-wily-15-10

Command line code from site: `sudo apt-get install openjfx`

**Comment by kayler-renslow** [comment]
With Arma Dialog Creator being bundled with 2.0.0 and future versions, the color picker is no longer supported or available.
