### ISSUE TITLE
How install

### ISSUE THREAD

**Issue by testerfr810** [kayler-renslow/arma-intellij-plugin#76]
tried to install, no found in repo & when i want install manually i nothing no syntax ?

ty

**Comment by kayler-renslow** [comment]
Hi. There are instructions on how to install this here: https://forums.bohemia.net/forums/topic/190427-arma-intellij-plugin-smart-editing-for-header-and-sqf-files/

**Comment by rebruCH** [comment]
Install instruction doesnt help - got the same. Installed it over disk (because 404 on jetbrains plugin repo) but it doesnt work properly.

induced.txt
```
Following exceptions happened soon after this one, most probably they are induced.


2021-11-07T22:50:19.094
java.lang.NoClassDefFoundError: Could not initialize class com.kaylerrenslow.armaplugin.lang.sqf.psi.SQFSyntaxHelper
	at com.kaylerrenslow.armaplugin.lang.sqf.psi.inspections.SQFSyntaxAndTypeCheckingInspection$1.visitStatement(SQFSyntaxAndTypeCheckingInspection.java:31)
	at com.kaylerrenslow.armaplugin.lang.sqf.psi.SQFPsiVisitor.visitExpressionStatement(SQFPsiVisitor.java:59)
	at com.kaylerrenslow.armaplugin.lang.sqf.psi.impl.SQFPsiExpressionStatementImpl.accept(SQFPsiExpressionStatementImpl.java:21)
	at com.kaylerrenslow.armaplugin.lang.sqf.psi.impl.SQFPsiExpressionStatementImpl.accept(SQFPsiExpressionStatementImpl.java:25)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:64)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:55)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:326)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:285)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:283)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:283)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

stacktrace.txt
```
java.lang.NoClassDefFoundError: com/kaylerrenslow/armaDialogCreator/util/XmlUtil
	at com.kaylerrenslow.armaplugin.lang.sqf.syntax.SQFCommandSyntaxXMLLoader.importFromStream(SQFCommandSyntaxXMLLoader.java:41)
	at com.kaylerrenslow.armaplugin.lang.sqf.syntax.CommandDescriptor.getDescriptorFromFile(CommandDescriptor.java:21)
	at com.kaylerrenslow.armaplugin.lang.sqf.syntax.CommandDescriptorPool.<init>(CommandDescriptorPool.java:95)
	at com.kaylerrenslow.armaplugin.lang.sqf.psi.SQFSyntaxHelper.<init>(SQFSyntaxHelper.java:27)
	at com.kaylerrenslow.armaplugin.lang.sqf.psi.SQFSyntaxHelper.<clinit>(SQFSyntaxHelper.java:20)
	at com.kaylerrenslow.armaplugin.lang.sqf.psi.inspections.SQFSyntaxAndTypeCheckingInspection$1.visitStatement(SQFSyntaxAndTypeCheckingInspection.java:31)
	at com.kaylerrenslow.armaplugin.lang.sqf.psi.SQFPsiVisitor.visitExpressionStatement(SQFPsiVisitor.java:59)
	at com.kaylerrenslow.armaplugin.lang.sqf.psi.impl.SQFPsiExpressionStatementImpl.accept(SQFPsiExpressionStatementImpl.java:21)
	at com.kaylerrenslow.armaplugin.lang.sqf.psi.impl.SQFPsiExpressionStatementImpl.accept(SQFPsiExpressionStatementImpl.java:25)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:64)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:55)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:326)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:285)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:283)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:283)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: com.kaylerrenslow.armaDialogCreator.util.XmlUtil PluginClassLoader(plugin=PluginDescriptor(name=Arma IntelliJ Plugin, id=com.kaylerrenslow.plugin.armaplugin.id, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2021.2\plugins\Arma Intellij Plugin.jar, version=2.0.2, package=null), packagePrefix=null, instanceId=117, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 37 more
```
